name: "Terraform Plan"

on:
  pull_request:
    types: [opened, synchronize, reopened] 
    branches: ["main"]
    paths: ["main/**", ".github/workflows/ci-terraform-plan-infra-main.yaml"]
  workflow_dispatch:

env:
  TF_VAR_private_key: ${{ secrets.TF_VAR_PRIVATE_KEY }}
  TF_VAR_public_key: ${{ secrets.TF_VAR_PUBLIC_KEY }}
  TF_VAR_db_fiap_x_username: ${{ secrets.TF_VAR_DB_FIAP_X_USERNAME}}
  TF_VAR_db_fiap_x_user_password: ${{ secrets.TF_VAR_DB_FIAP_X_USER_PASSWORD }}

jobs: 
  terraform:
    name: "Terraform Plan"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2.0.0  
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
      
      - name: Terraform init
        working-directory: ./main
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        working-directory: ./main
        run: terraform plan -no-color
        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1
